version: 1.0.{build}
image: Visual Studio 2017
init:
- cmd: >-
    set PATH=%QTDIR%\bin;%PATH%

    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
environment:
  matrix:
  - QTDIR: C:\Qt\5.9\msvc2017_64
  - QTDIR: C:\Qt\5.12\msvc2017_64
install:
- ps: >-
    mkdir redis-3.2.100

    ./redis4appveyor.ps1
build_script:
- cmd: >-
    git submodule update --init --recursive

    cd 3rdparty\hiredis

    git apply ..\hiredis-win.patch

    cd ..\..

    qmake -v

    qmake "CONFIG+=qredisclientshared"

    nmake release

    cd tests\unit_tests

    qmake "CONFIG+=qredisclientshared" DEFINES+=INTEGRATION_TESTS

    nmake release
    
    copy ..\..\qredisclient0.dll

    cd ..\..
test_script:
- cmd: >-
    cd tests\unit_tests

    .\tests.exe -xunitxml -o TEST-results.xml

on_finish:
- ps: >-
    $wc = New-Object 'System.Net.WebClient'

    $uri = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"

    $Dir = "$($env:APPVEYOR_BUILD_FOLDER)\tests\unit_tests"

    cd $Dir

    dir .


    echo "Publish tests in $Dir to $uri"

    foreach($item in (gci $Dir "*.xml" | % name))

    {

      echo "Publishing $item"

      $resp = $wc.UploadFile($uri, (Resolve-Path $item))
      
      Write-Output $resp

    }
